### ISSUE TITLE
Hey, I don't like those bins.

### ISSUE THREAD

**Issue by tailot** [eahlstrom/dnslogger#2]
This is the content of the binary!
![Schermata del 2019-10-20 22-46-50](https://user-images.githubusercontent.com/40148896/67165978-8f330500-f38b-11e9-8c9e-63f37ac6fa72.png)
![image](https://user-images.githubusercontent.com/40148896/67165998-c30e2a80-f38b-11e9-9601-ad1429404161.png)

**Comment by eahlstrom** [comment]
No worries. It's used in a test to verify that we can handle looping pointers.
The "raw" packet are simulated to be evil.
-- snipp --
dnslogger(master) $ git grep evilname
Binary file fixtures/dns/dns_looping_pointer.bin matches
dnslogger(master) $ git grep -B3 -A4 dns_looping_pointer
src/parse/dns/dns_message.rs-    #[test]
src/parse/dns/dns_message.rs-    fn test_should_handle_looping_pointers() {
src/parse/dns/dns_message.rs-        #[allow(unused_variables)]
src/parse/dns/dns_message.rs:        let dns_data: &[u8] = include_bytes!("../../../fixtures/dns/dns_looping_pointer.bin");
src/parse/dns/dns_message.rs-        let (_rest, dns_message) = dns_message(dns_data, false).unwrap();
src/parse/dns/dns_message.rs-        println!("{:?}", dns_message);
src/parse/dns/dns_message.rs-        assert!(true);
src/parse/dns/dns_message.rs-    }

**Comment by tailot** [comment]
I was just making sure of your awareness. Thank you
